-- 코드를 작성해주세요
#item_id로 조인 하는데? NULL인 애만 조인-> 정렬
SELECT INFO.ITEM_ID,INFO.ITEM_NAME
FROM ITEM_INFO AS INFO
INNER JOIN (SELECT *
           FROM ITEM_TREE AS IT
           WHERE IT.PARENT_ITEM_ID IS NULL) AS NEW_IT
ON NEW_IT.ITEM_ID = INFO.ITEM_ID
ORDER BY ITEM_ID