-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS AS INS 
inner join ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID AND INS.SEX_UPON_INTAKE like"intact%"
AND (OUTS.SEX_UPON_OUTCOME LIKE("Neutered%") or OUTS.SEX_UPON_OUTCOME LIKE("spayed%") )

