-- 코드를 입력하세요
#조인을 하고 가장 리뷰 많이 작성한 회워
SELECT MEMBER_NAME, REVIEW_TEXT,DATE_FORMAT(RES.REVIEW_DATE, '%Y-%m-%d') AS FORMATTED_REVIEW_DATE
FROM MEMBER_PROFILE AS PRO
INNER JOIN REST_REVIEW AS RES 
ON RES.MEMBER_ID = PRO.MEMBER_ID
WHERE PRO.MEMBER_ID = (SELECT MEMBER_ID
                 FROM REST_REVIEW
                 GROUP BY REST_REVIEW.MEMBER_ID
                 ORDER BY COUNT(*) DESC
                 LIMIT 1)
ORDER BY REVIEW_DATE ,REVIEW_TEXT