# -- 코드를 작성해주세요
# 연도별 가장큰 대장균 크기 구하기
# 대장균 크기의 편차를 구함 

SELECT ED.YEAR, ED.MAX_SIZE- ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA
JOIN(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS ED
ON ED.YEAR = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)
ORDER BY YEAR,YEAR_DEV ASC