
SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F
JOIN (SELECT FISH_TYPE,MAX(LENGTH) AS MA
     FROM FISH_INFO AS F
     GROUP BY FISH_TYPE) AS J 
ON F.FISH_TYPE = J.FISH_TYPE
JOIN FISH_NAME_INFO AS N
ON N.FISH_TYPE = F.FISH_TYPE
WHERE F.LENGTH = J.MA
     
     