-- 코드를 작성해주세요
#물고기 평균33넘는애들만 프롬절에서 걸러
#그룹바이 해서 카운트, 맥스 , 종류는 인덱스

SELECT COUNT(*)AS FISH_COUNT,MAX(INFO.LENGTH) AS MAX_LENGTH,INFO.FISH_TYPE
FROM FISH_INFO AS INFO
JOIN (SELECT FISH_TYPE, AVG(LENGTH) AS LENG
     FROM FISH_INFO
     GROUP BY FISH_INFO.FISH_TYPE
     HAVING AVG(CASE WHEN LENGTH<= 10 THEN 10 ELSE LENGTH END)>=33) AS FISH
ON INFO.FISH_TYPE = FISH.FISH_TYPE
group by  INFO.FISH_TYPE
ORDER BY FISH_TYPE